#!/usr/bin/env ruby
require "#{File.dirname(File.realpath(__FILE__))}/app/app.rb"
require 'logger'

LOGGER = Logger.new(STDOUT)
LOGGER.level = Logger::INFO
## Main
def main
  LOGGER.info "Starting application..."

  ## DOING STUFF HERE
  tic_tac_toe = TicTacToeGame.new
  tic_tac_toe.start_game

  LOGGER.info "Applications ended.\nALL DONE!"
end

## Main Excecution
main